server:
  port: 8086
spring:
  output:
    ansi:
      enabled: always
  task:
    execution:
      pool:
        queue-capacity: 9999
        keep-alive: 30s
        core-size: 8
        max-size: 50
        allow-core-thread-timeout: true
      thread-name-prefix: znld-web-task-thread
    scheduling:
      pool:
        size: 5
      thread-name-prefix: znld-web-task-scheduling-thread
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    banner-mode: "off"
  profiles:
    include: onenet
    active: dev
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
project:
  name: znld
  cache-prefix: 'znld::web::service::cache'
  cache-of-null-expiration-time: 5s
  cache-of-captcha-expiration-time: 30s
  auth2-token-expiration-time: 7d
  captcha-expiration-time: 30s
