version: '3.7'
services:
  api:
    container_name: znld-etcd
    image: quay.io/coreos/etcd:v3.3.13
    restart: on-failure
    ports:
      - target: 2379
        published: 2379
        protocol: tcp
        mode: host
      - target: 2380
        published: 2380
        protocol: tcp
        mode: host
      - target: 4001
        published: 4001
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      ETCD_ADVERTISE_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
      ETCDCTL_API: "3"
    networks:
      - znld-network
networks:
  znld-network:
    driver: bridge
    name: znld-net