version: '3.7'
services:
  redis:
    container_name: znld-redis-environment
    image: redis:5.0.5
    restart: on-failure
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
      - type: bind
        source: ./redis.conf
        target: /usr/local/etc/redis/redis.conf
      - type: bind
        source: ./data
        target: /data
    ports:
      - target: 6379
        published: 8383
        protocol: tcp
        mode: host
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - znld-network
networks:
  znld-network:
    driver: bridge
    name: znld-net