version: '3.7'
services:
  xxl-job-admin:
    container_name: znld-xxl-job-admin
    image: xuxueli/xxl-job-admin:2.1.2
    ports:
      - target: 8080
        published: 7070
        protocol: tcp
        mode: host
    restart: on-failure
    environment:
      PARAMS: >-
        --spring.datasource.url=jdbc:mysql://192.168.11.101:8307/xxl_job?Unicode=true&characterEncoding=UTF-8
        --spring.datasource.username=root
        --spring.datasource.password=znld@DB#188188
    volumes:
      - type: bind
        source: ./applogs
        target: /data/applogs
    networks:
      - znld-network
networks:
  znld-network:
    driver: bridge
    name: znld-net