db-server: 192.168.68.128:3306
redis-server: 192.168.68.128
redis-server-port: 8000

server:
  port: 8181
spring:
  datasource:
    #useAffectedRows的作用，当使用 UPDATE 查询，MySQL 不会将原值和新值一样的列更新，改成true，即返回更改的行数，而非匹配的行数
    url: jdbc:mysql://${db-server}/znld?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
    username: root
    password: 123456
  redis:
    host: ${redis-server}
    port: ${redis-server-port}
    #password: 123456
    ssl: false
    timeout: 2s
    cluster:
      nodes:
    sentinel:
      master:
      nodes: