server:
  port: 8089
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    banner-mode: "off"
  profiles:
    include:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
baidu-ak: x1ySji2AxajkmThvd8weGwOQ
