onenet-server: http://api.heclouds.com
znld:
  onenet:
    getHistoryDataStreamUrl: ${onenet-server}/devices/{deviceId}/datapoints
    postExecuteUrl: ${onenet-server}/nbiot/execute
    offlineExecuteUrl: ${onenet-server}/nbiot/execute/offline
    getLastDataStreamUrl: ${onenet-server}/devices/datapoints?devIds={devIds}
    getDeviceUrl: ${onenet-server}/devices/{deviceId}
    getDataStreamByIdUrl: ${onenet-server}/devices/{deviceId}/datastreams/{datastreamId}
    getDataStreamsByIdsUrl: ${onenet-server}/devices/{deviceId}/datastreams?datastream_ids={dataStreamIds}
    writeValueUrl: ${onenet-server}/nbiot
    readValueUrl: ${onenet-server}/nbiot