server:
  port: 8089
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    banner-mode: "off"
  profiles:
    include: onenet
    active: dev
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
scheduled:
  cron: "0 */1 * * * ?"
baidu-ak: x1ySji2AxajkmThvd8weGwOQ
zone-id : Asia/Shanghai
max-try: 10
jobs:
  enabled: false
