server:
  port: 8089
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    banner-mode: "off"
  profiles:
    include: onenet
    active: prod
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
schedule:
  enabled: true
  cron: "0 */1 * * * ?"
  fixed-delay-waiting: 3000
  fixed-delay-failed: 10000
baidu-ak: x1ySji2AxajkmThvd8weGwOQ
zone-id : Asia/Shanghai
max-try: 10
