auth-server: http://58.210.51.74:8081 # 认证服务器地址
security:
  oauth2:
    client:
      client-id: sybd_znld_test
      client-secret: defadfc2ad2fbb4fbcdc4d64f6c8d823
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
      id: znld-web