server:
  port: 8084
spring:
  profiles:
    include: onenet
    active: prod
  rabbitmq:
    username: admin
    password: admin123
    virtual-host: /
schedule:
  enabled: true
  cron: "0 */1 * * * ?"
  fixed-delay-waiting: 3000
  fixed-delay-failed: 10000
baidu-ak: x1ySji2AxajkmThvd8weGwOQ
