server:
  port: 8084
spring:
  profiles:
    include: onenet
    active: prod
  rabbitmq:
    username: admin
    password: admin123
    virtual-host: /
schedule:
  enabled: false
  cron: "0 0 */1 * * ?"
  fixed-delay-waiting: 3000
  fixed-delay-failed: 10000
baidu-ak: x1ySji2AxajkmThvd8weGwOQ
max-offline-hours: 12
xxl:
  job:
    accessToken:
    executor:
      appname: znld-onenet
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30