auth-server: http://localhost:8888 # 认证服务器地址

server:
  port: 8081
security:
  oauth2:
    client:
      client-id: znld
      client-secret: 2018
      access-token-uri: ${auth-server}/oauth/token
      user-authorization-uri: ${auth-server}/oauth/authorize
    resource:
      token-info-uri: ${auth-server}/oauth/check_token
      id: znld-web
spring:
  redis:
    host: 192.168.1.229
    port: 6379
  main:
    banner-mode: "off"
  session:
    timeout: 30m
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true