version: '3.7'
services:
  api:
    container_name: znld-rabbitmq
    image: rabbitmq:3.7.18-management
    restart: on-failure
    ports:
      - target: 5672
        published: 5672
        protocol: tcp
        mode: host
      - target: 15672
        published: 15672
        protocol: tcp
        mode: host
    volumes:
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - znld-network
networks:
  znld-network:
    driver: bridge
    name: znld-net