server:
  port: 8086
spring:
  resources:
    add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  main:
    banner-mode: "off"
  profiles:
    include:
    active: prod
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
baidu-ak: x1ySji2AxajkmThvd8weGwOQ
dubbo:
  application:
    name: dubbo-app
  scan:
    base-packages: com.sybd.znld.environment.service
  registry:
    address: 192.168.11.101:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 12345
