db-server: 58.210.51.74:8306
redis-server: 58.210.51.74
redis-server-port: 8000

spring:
  redis:
    host: ${redis-server}
    port: ${redis-server-port}
  datasource:
    druid:
      oauth:
        #useAffectedRows的作用，当使用 UPDATE 查询，MySQL 不会将原值和新值一样的列更新，改成true，即返回更改的行数，而非匹配的行数
        url: jdbc:mysql://${db-server}/oauth?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
        username: root
        password: znld@DB#188188
      znld:
        #useAffectedRows的作用，当使用 UPDATE 查询，MySQL 不会将原值和新值一样的列更新，改成true，即返回更改的行数，而非匹配的行数
        url: jdbc:mysql://${db-server}/ZNLD_V2?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
        username: root
        password: znld@DB#188188
      rbac:
        url: jdbc:mysql://${db-server}/RBAC?characterEncoding=utf-8&useSSL=false&useAffectedRows=true&allowPublicKeyRetrieval=true
        username: root
        password: znld@DB#188188