db-server: localhost:8306
redis-server: localhost
redis-server-port: 7379

spring:
  redis:
    host: ${redis-server}
    port: ${redis-server-port}
  datasource:
    druid:
      oauth:
        #useAffectedRows的作用，当使用 UPDATE 查询，MySQL 不会将原值和新值一样的列更新，改成true，即返回更改的行数，而非匹配的行数
        url: jdbc:mysql://${db-server}/oauth?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
        username: sybd
        password: znld@DB#188188
      znld:
        #useAffectedRows的作用，当使用 UPDATE 查询，MySQL 不会将原值和新值一样的列更新，改成true，即返回更改的行数，而非匹配的行数
        url: jdbc:mysql://${db-server}/znld?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
        username: sybd
        password: znld@DB#188188