server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter:
        stat:
          enabled: true
          log-slow-sql: true
          slow-sql-millis: 2000
        wall:
          enabled: true
          config:
            delete-allow: false
            alter-table-allow: false
            drop-table-allow: false
            rename-table-allow: false
            create-table-allow: false
            delete-where-none-check: true
            delete-where-alway-true-check: true
            update-where-alay-true-check: true
            update-where-none-check: true
        slf4j:
          enabled: true
          statement-log-enabled: true
          result-set-log-enabled: true
          data-source-log-enabled: true
          connection-log-enabled: true
          statement-sql-pretty-format: true
          statement-prepare-after-log-enabled: true
          statement-prepare-call-after-log-enabled: true
          statement-executable-sql-log-enable: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: ["*.gif", "*.png", "*.jpg", "*.html", "*.js", "*.css", "*.ico", "/druid/*"]
      stat-view-servlet: #http://localhost:8080/druid/
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: 123456
        allow: localhost
      db-type: mysql
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      validation-query: select 1
      reset-stat-enable: false
  main:
    banner-mode: "off"
  session:
    timeout: 30m
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
  profiles:
    include:
    active: dev
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.sybd.security.oauth2.server.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: true
    logic-not-delete-value: false
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    banner: false
  configuration:
    map-underscore-to-camel-case: true