server:
  port: 8081
spring:
  main:
    banner-mode: "off"
  session:
    timeout: 30m
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: true
  profiles:
    include:
    active: prod
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.sybd.security.oauth2.server.model
  configuration:
    map-underscore-to-camel-case: true