db-server: 192.168.1.250:3306
redis-server: 192.168.1.250
redis-server-port: 7379

spring:
  redis:
    host: ${redis-server}
    port: ${redis-server-port}
  datasource:
    druid:
      oauth:
        #useAffectedRows的作用，当使用 UPDATE 查询，MySQL 不会将原值和新值一样的列更新，改成true，即返回更改的行数，而非匹配的行数
        url: jdbc:mysql://${db-server}/oauth?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
        username: root
        password: 123456
      znld:
        #useAffectedRows的作用，当使用 UPDATE 查询，MySQL 不会将原值和新值一样的列更新，改成true，即返回更改的行数，而非匹配的行数
        url: jdbc:mysql://${db-server}/znld?characterEncoding=utf-8&useSSL=false&useAffectedRows=true
        username: root
        password: 123456