server:
  port: 8081
spring:
  main:
    banner-mode: "off"
  session:
    timeout: 30m
  profiles:
    include:
    active: dev
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true